[
  {
    "response": "Afganistán",
    "paiscode": 93,
    "code": "AF",
    "foto": "https://flagcdn.com/af.svg",
    "emoji": "🇦🇫",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Albania",
    "paiscode": 355,
    "code": "AL",
    "foto": "https://flagcdn.com/al.svg",
    "emoji": "🇦🇱",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Alemania",
    "paiscode": 49,
    "code": "DE",
    "foto": "https://flagcdn.com/de.svg",
    "emoji": "🇩🇪",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "Andorra",
    "paiscode": 376,
    "code": "AD",
    "foto": "https://flagcdn.com/ad.svg",
    "emoji": "🇦🇩",
    "latinAmerica": false,
    "phoneLength": 6,
  },
  {
    "response": "Angola",
    "paiscode": 244,
    "code": "AO",
    "foto": "https://flagcdn.com/ao.svg",
    "emoji": "🇦🇴",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Antigua y Barbuda",
    "paiscode": 1268,
    "code": "AG",
    "foto": "https://flagcdn.com/ag.svg",
    "emoji": "🇦🇬",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "Arabia Saudita",
    "paiscode": 966,
    "code": "SA",
    "foto": "https://flagcdn.com/sa.svg",
    "emoji": "🇸🇦",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Argelia",
    "paiscode": 213,
    "code": "DZ",
    "foto": "https://flagcdn.com/dz.svg",
    "emoji": "🇩🇿",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Argentina",
    "paiscode": 54,
    "code": "AR",
    "foto": "https://flagcdn.com/ar.svg",
    "emoji": "🇦🇷",
    "latinAmerica": true,
    "phoneLength": 8,
  },
  {
    "response": "Armenia",
    "paiscode": 374,
    "code": "AM",
    "foto": "https://flagcdn.com/am.svg",
    "emoji": "🇦🇲",
    "latinAmerica": false,
    "phoneLength": 6,
  },
  {
    "response": "Australia",
    "paiscode": 61,
    "code": "AU",
    "foto": "https://flagcdn.com/au.svg",
    "emoji": "🇦🇺",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Austria",
    "paiscode": 43,
    "code": "AT",
    "foto": "https://flagcdn.com/at.svg",
    "emoji": "🇦🇹",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Azerbaiyán",
    "paiscode": 994,
    "code": "AZ",
    "foto": "https://flagcdn.com/az.svg",
    "emoji": "🇦🇿",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Bahamas",
    "paiscode": 1242,
    "code": "BS",
    "foto": "https://flagcdn.com/bs.svg",
    "emoji": "🇧🇸",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "Bangladés",
    "paiscode": 880,
    "code": "BD",
    "foto": "https://flagcdn.com/bd.svg",
    "emoji": "🇧🇩",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "Barbados",
    "paiscode": 1246,
    "code": "BB",
    "foto": "https://flagcdn.com/bb.svg",
    "emoji": "🇧🇧",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "Baréin",
    "paiscode": 973,
    "code": "BH",
    "foto": "https://flagcdn.com/bh.svg",
    "emoji": "🇧🇭",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Bélgica",
    "paiscode": 32,
    "code": "BE",
    "foto": "https://flagcdn.com/be.svg",
    "emoji": "🇧🇪",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Belice",
    "paiscode": 501,
    "code": "BZ",
    "foto": "https://flagcdn.com/bz.svg",
    "emoji": "🇧🇿",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Benín",
    "paiscode": 229,
    "code": "BJ",
    "foto": "https://flagcdn.com/bj.svg",
    "emoji": "🇧🇯",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Bielorrusia",
    "paiscode": 375,
    "code": "BY",
    "foto": "https://flagcdn.com/by.svg",
    "emoji": "🇧🇾",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Birmania",
    "paiscode": 95,
    "code": "MM",
    "foto": "https://flagcdn.com/mm.svg",
    "emoji": "🇲🇲",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "Bolivia",
    "paiscode": 591,
    "code": "BO",
    "foto": "https://flagcdn.com/bo.svg",
    "emoji": "🇧🇴",
    "latinAmerica": true,
    "phoneLength": 9,
  },
  {
    "response": "Bosnia y Herzegovina",
    "paiscode": 387,
    "code": "BA",
    "foto": "https://flagcdn.com/ba.svg",
    "emoji": "🇧🇦",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Botsuana",
    "paiscode": 267,
    "code": "BW",
    "foto": "https://flagcdn.com/bw.svg",
    "emoji": "🇧🇼",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Brasil",
    "paiscode": 55,
    "code": "BR",
    "foto": "https://flagcdn.com/br.svg",
    "emoji": "🇧🇷",
    "latinAmerica": true,
    "phoneLength": 11,
  },
  {
    "response": "Brunéi",
    "paiscode": 673,
    "code": "BN",
    "foto": "https://flagcdn.com/bn.svg",
    "emoji": "🇧🇳",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Bulgaria",
    "paiscode": 359,
    "code": "BG",
    "foto": "https://flagcdn.com/bg.svg",
    "emoji": "🇧🇬",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Burkina Faso",
    "paiscode": 226,
    "code": "BF",
    "foto": "https://flagcdn.com/bf.svg",
    "emoji": "🇧🇫",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Burundi",
    "paiscode": 257,
    "code": "BI",
    "foto": "https://flagcdn.com/bi.svg",
    "emoji": "🇧🇮",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Bután",
    "paiscode": 975,
    "code": "BT",
    "foto": "https://flagcdn.com/bt.svg",
    "emoji": "🇧🇹",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Cabo Verde",
    "paiscode": 238,
    "code": "CV",
    "foto": "https://flagcdn.com/cv.svg",
    "emoji": "🇨🇻",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Camboya",
    "paiscode": 855,
    "code": "KH",
    "foto": "https://flagcdn.com/kh.svg",
    "emoji": "🇰🇭",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Camerún",
    "paiscode": 237,
    "code": "CM",
    "foto": "https://flagcdn.com/cm.svg",
    "emoji": "🇨🇲",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Canadá",
    "paiscode": 1,
    "code": "CA",
    "foto": "https://flagcdn.com/ca.svg",
    "emoji": "🇨🇦",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "Catar",
    "paiscode": 974,
    "code": "QA",
    "foto": "https://flagcdn.com/qa.svg",
    "emoji": "🇶🇦",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Chad",
    "paiscode": 235,
    "code": "TD",
    "foto": "https://flagcdn.com/td.svg",
    "emoji": "🇹🇩",
    "latinAmerica": false,
    "phoneLength": 6,
  },
  {
    "response": "Chile",
    "paiscode": 56,
    "code": "CL",
    "foto": "https://flagcdn.com/cl.svg",
    "emoji": "🇨🇱",
    "latinAmerica": true,
    "phoneLength": 9,
  },
  {
    "response": "China",
    "paiscode": 86,
    "code": "CN",
    "foto": "https://flagcdn.com/cn.svg",
    "emoji": "🇨🇳",
    "latinAmerica": false,
    "phoneLength": 11,
  },
  {
    "response": "Chipre",
    "paiscode": 357,
    "code": "CY",
    "foto": "https://flagcdn.com/cy.svg",
    "emoji": "🇨🇾",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Colombia",
    "paiscode": 57,
    "code": "CO",
    "foto": "https://flagcdn.com/co.svg",
    "emoji": "🇨🇴",
    "latinAmerica": true,
    "phoneLength": 10,
  },
  {
    "response": "Comoras",
    "paiscode": 269,
    "code": "KM",
    "foto": "https://flagcdn.com/km.svg",
    "emoji": "🇰🇲",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Congo",
    "paiscode": 242,
    "code": "CG",
    "foto": "https://flagcdn.com/cg.svg",
    "emoji": "🇨🇬",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Corea del Norte",
    "paiscode": 850,
    "code": "KP",
    "foto": "https://flagcdn.com/kp.svg",
    "emoji": "🇰🇵",
    "latinAmerica": false,
    "phoneLength": 13,
  },
  {
    "response": "Corea del Sur",
    "paiscode": 82,
    "code": "KR",
    "foto": "https://flagcdn.com/kr.svg",
    "emoji": "🇰🇷",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Costa de Marfil",
    "paiscode": 225,
    "code": "CI",
    "foto": "https://flagcdn.com/ci.svg",
    "emoji": "🇨🇮",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Costa Rica",
    "paiscode": 506,
    "code": "CR",
    "foto": "https://flagcdn.com/cr.svg",
    "emoji": "🇨🇷",
    "latinAmerica": true,
    "phoneLength": 8,
  },
  {
    "response": "Croacia",
    "paiscode": 385,
    "code": "HR",
    "foto": "https://flagcdn.com/hr.svg",
    "emoji": "🇭🇷",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Cuba",
    "paiscode": 53,
    "code": "CU",
    "foto": "https://flagcdn.com/cu.svg",
    "emoji": "🇨🇺",
    "latinAmerica": true,
    "phoneLength": 8,
  },
  {
    "response": "Dinamarca",
    "paiscode": 45,
    "code": "DK",
    "foto": "https://flagcdn.com/dk.svg",
    "emoji": "🇩🇰",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Dominica",
    "paiscode": 1767,
    "code": "DM",
    "foto": "https://flagcdn.com/dm.svg",
    "emoji": "🇩🇲",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "Ecuador",
    "paiscode": 593,
    "code": "EC",
    "foto": "https://flagcdn.com/ec.svg",
    "emoji": "🇪🇨",
    "latinAmerica": true,
    "phoneLength": 9,
  },
  {
    "response": "Egipto",
    "paiscode": 20,
    "code": "EG",
    "foto": "https://flagcdn.com/eg.svg",
    "emoji": "🇪🇬",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "El Salvador",
    "paiscode": 503,
    "code": "SV",
    "foto": "https://flagcdn.com/sv.svg",
    "emoji": "🇸🇻",
    "latinAmerica": true,
    "phoneLength": 8,
  },
  {
    "response": "Emiratos Árabes Unidos",
    "paiscode": 971,
    "code": "AE",
    "foto": "https://flagcdn.com/ae.svg",
    "emoji": "🇦🇪",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Eritrea",
    "paiscode": 291,
    "code": "ER",
    "foto": "https://flagcdn.com/er.svg",
    "emoji": "🇪🇷",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Eslovaquia",
    "paiscode": 421,
    "code": "SK",
    "foto": "https://flagcdn.com/sk.svg",
    "emoji": "🇸🇰",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Eslovenia",
    "paiscode": 386,
    "code": "SI",
    "foto": "https://flagcdn.com/si.svg",
    "emoji": "🇸🇮",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "España",
    "paiscode": 34,
    "code": "ES",
    "foto": "https://flagcdn.com/es.svg",
    "emoji": "🇪🇸",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Estados Unidos",
    "paiscode": 1,
    "code": "US",
    "foto": "https://flagcdn.com/us.svg",
    "emoji": "🇺🇸",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "Estonia",
    "paiscode": 372,
    "code": "EE",
    "foto": "https://flagcdn.com/ee.svg",
    "emoji": "🇪🇪",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Etiopía",
    "paiscode": 251,
    "code": "ET",
    "foto": "https://flagcdn.com/et.svg",
    "emoji": "🇪🇹",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Filipinas",
    "paiscode": 63,
    "code": "PH",
    "foto": "https://flagcdn.com/ph.svg",
    "emoji": "🇵🇭",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "Finlandia",
    "paiscode": 358,
    "code": "FI",
    "foto": "https://flagcdn.com/fi.svg",
    "emoji": "🇫🇮",
    "latinAmerica": false,
    "phoneLength": 11,
  },
  {
    "response": "Fiyi",
    "paiscode": 679,
    "code": "FJ",
    "foto": "https://flagcdn.com/fj.svg",
    "emoji": "🇫🇯",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Francia",
    "paiscode": 33,
    "code": "FR",
    "foto": "https://flagcdn.com/fr.svg",
    "emoji": "🇫🇷",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Gabón",
    "paiscode": 241,
    "code": "GA",
    "foto": "https://flagcdn.com/ga.svg",
    "emoji": "🇬🇦",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Gambia",
    "paiscode": 220,
    "code": "GM",
    "foto": "https://flagcdn.com/gm.svg",
    "emoji": "🇬🇲",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Georgia",
    "paiscode": 995,
    "code": "GE",
    "foto": "https://flagcdn.com/ge.svg",
    "emoji": "🇬🇪",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Ghana",
    "paiscode": 233,
    "code": "GH",
    "foto": "https://flagcdn.com/gh.svg",
    "emoji": "🇬🇭",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Granada",
    "paiscode": 1473,
    "code": "GD",
    "foto": "https://flagcdn.com/gd.svg",
    "emoji": "🇬🇩",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "Grecia",
    "paiscode": 30,
    "code": "GR",
    "foto": "https://flagcdn.com/gr.svg",
    "emoji": "🇬🇷",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "Guatemala",
    "paiscode": 502,
    "code": "GT",
    "foto": "https://flagcdn.com/gt.svg",
    "emoji": "🇬🇹",
    "latinAmerica": true,
    "phoneLength": 8,
  },
  {
    "response": "Guinea",
    "paiscode": 224,
    "code": "GN",
    "foto": "https://flagcdn.com/gn.svg",
    "emoji": "🇬🇳",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Guinea-Bisáu",
    "paiscode": 245,
    "code": "GW",
    "foto": "https://flagcdn.com/gw.svg",
    "emoji": "🇬🇼",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Guinea Ecuatorial",
    "paiscode": 240,
    "code": "GQ",
    "foto": "https://flagcdn.com/gq.svg",
    "emoji": "🇬🇶",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Guyana",
    "paiscode": 592,
    "code": "GY",
    "foto": "https://flagcdn.com/gy.svg",
    "emoji": "🇬🇾",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Haití",
    "paiscode": 509,
    "code": "HT",
    "foto": "https://flagcdn.com/ht.svg",
    "emoji": "🇭🇹",
    "latinAmerica": true,
    "phoneLength": 8,
  },
  {
    "response": "Honduras",
    "paiscode": 504,
    "code": "HN",
    "foto": "https://flagcdn.com/hn.svg",
    "emoji": "🇭🇳",
    "latinAmerica": true,
    "phoneLength": 8,
  },
  {
    "response": "Hungría",
    "paiscode": 36,
    "code": "HU",
    "foto": "https://flagcdn.com/hu.svg",
    "emoji": "🇭🇺",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "India",
    "paiscode": 91,
    "code": "IN",
    "foto": "https://flagcdn.com/in.svg",
    "emoji": "🇮🇳",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "Indonesia",
    "paiscode": 62,
    "code": "ID",
    "foto": "https://flagcdn.com/id.svg",
    "emoji": "🇮🇩",
    "latinAmerica": false,
    "phoneLength": 11,
  },
  {
    "response": "Irak",
    "paiscode": 964,
    "code": "IQ",
    "foto": "https://flagcdn.com/iq.svg",
    "emoji": "🇮🇶",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "Irán",
    "paiscode": 98,
    "code": "IR",
    "foto": "https://flagcdn.com/ir.svg",
    "emoji": "🇮🇷",
    "latinAmerica": false,
    "phoneLength": 11,
  },
  {
    "response": "Irlanda",
    "paiscode": 353,
    "code": "IE",
    "foto": "https://flagcdn.com/ie.svg",
    "emoji": "🇮🇪",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Islandia",
    "paiscode": 354,
    "code": "IS",
    "foto": "https://flagcdn.com/is.svg",
    "emoji": "🇮🇸",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Islas Marshall",
    "paiscode": 692,
    "code": "MH",
    "foto": "https://flagcdn.com/mh.svg",
    "emoji": "🇲🇭",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Islas Salomón",
    "paiscode": 677,
    "code": "SB",
    "foto": "https://flagcdn.com/sb.svg",
    "emoji": "🇸🇧",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Israel",
    "paiscode": 972,
    "code": "IL",
    "foto": "https://flagcdn.com/il.svg",
    "emoji": "🇮🇱",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Italia",
    "paiscode": 39,
    "code": "IT",
    "foto": "https://flagcdn.com/it.svg",
    "emoji": "🇮🇹",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "Jamaica",
    "paiscode": 1876,
    "code": "JM",
    "foto": "https://flagcdn.com/jm.svg",
    "emoji": "🇯🇲",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "Japón",
    "paiscode": 81,
    "code": "JP",
    "foto": "https://flagcdn.com/jp.svg",
    "emoji": "🇯🇵",
    "latinAmerica": false,
    "phoneLength": 0,
  },
  {
    "response": "Jordania",
    "paiscode": 962,
    "code": "JO",
    "foto": "https://flagcdn.com/jo.svg",
    "emoji": "🇯🇴",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Kazajistán",
    "paiscode": 7,
    "code": "KZ",
    "foto": "https://flagcdn.com/kz.svg",
    "emoji": "🇰🇿",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "Kenia",
    "paiscode": 254,
    "code": "KE",
    "foto": "https://flagcdn.com/ke.svg",
    "emoji": "🇰🇪",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "Kirguistán",
    "paiscode": 996,
    "code": "KG",
    "foto": "https://flagcdn.com/kg.svg",
    "emoji": "🇰🇬",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Kiribati",
    "paiscode": 686,
    "code": "KI",
    "foto": "https://flagcdn.com/ki.svg",
    "emoji": "🇰🇮",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Kuwait",
    "paiscode": 965,
    "code": "KW",
    "foto": "https://flagcdn.com/kw.svg",
    "emoji": "🇰🇼",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Laos",
    "paiscode": 856,
    "code": "LA",
    "foto": "https://flagcdn.com/la.svg",
    "emoji": "🇱🇦",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Lesoto",
    "paiscode": 266,
    "code": "LS",
    "foto": "https://flagcdn.com/ls.svg",
    "emoji": "🇱🇸",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Letonia",
    "paiscode": 371,
    "code": "LV",
    "foto": "https://flagcdn.com/lv.svg",
    "emoji": "🇱🇻",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Líbano",
    "paiscode": 961,
    "code": "LB",
    "foto": "https://flagcdn.com/lb.svg",
    "emoji": "🇱🇧",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Liberia",
    "paiscode": 231,
    "code": "LR",
    "foto": "https://flagcdn.com/lr.svg",
    "emoji": "🇱🇷",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Libia",
    "paiscode": 218,
    "code": "LY",
    "foto": "https://flagcdn.com/ly.svg",
    "emoji": "🇱🇾",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "Liechtenstein",
    "paiscode": 423,
    "code": "LI",
    "foto": "https://flagcdn.com/li.svg",
    "emoji": "🇱🇮",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Lituania",
    "paiscode": 370,
    "code": "LT",
    "foto": "https://flagcdn.com/lt.svg",
    "emoji": "🇱🇹",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Luxemburgo",
    "paiscode": 352,
    "code": "LU",
    "foto": "https://flagcdn.com/lu.svg",
    "emoji": "🇱🇺",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Madagascar",
    "paiscode": 261,
    "code": "MG",
    "foto": "https://flagcdn.com/mg.svg",
    "emoji": "🇲🇬",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Malasia",
    "paiscode": 60,
    "code": "MY",
    "foto": "https://flagcdn.com/my.svg",
    "emoji": "🇲🇾",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Malaui",
    "paiscode": 265,
    "code": "MW",
    "foto": "https://flagcdn.com/mw.svg",
    "emoji": "🇲🇼",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Maldivas",
    "paiscode": 960,
    "code": "MV",
    "foto": "https://flagcdn.com/mv.svg",
    "emoji": "🇲🇻",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Malí",
    "paiscode": 223,
    "code": "ML",
    "foto": "https://flagcdn.com/ml.svg",
    "emoji": "🇲🇱",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Malta",
    "paiscode": 356,
    "code": "MT",
    "foto": "https://flagcdn.com/mt.svg",
    "emoji": "🇲🇹",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Marruecos",
    "paiscode": 212,
    "code": "MA",
    "foto": "https://flagcdn.com/ma.svg",
    "emoji": "🇲🇦",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Mauricio",
    "paiscode": 230,
    "code": "MU",
    "foto": "https://flagcdn.com/mu.svg",
    "emoji": "🇲🇺",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Mauritania",
    "paiscode": 222,
    "code": "MR",
    "foto": "https://flagcdn.com/mr.svg",
    "emoji": "🇲🇷",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "México",
    "paiscode": 52,
    "code": "MX",
    "foto": "https://flagcdn.com/mx.svg",
    "emoji": "🇲🇽",
    "latinAmerica": true,
    "phoneLength": 10,
  },
  {
    "response": "Micronesia",
    "paiscode": 691,
    "code": "FM",
    "foto": "https://flagcdn.com/fm.svg",
    "emoji": "🇫🇲",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Moldavia",
    "paiscode": 373,
    "code": "MD",
    "foto": "https://flagcdn.com/md.svg",
    "emoji": "🇲🇩",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Mónaco",
    "paiscode": 377,
    "code": "MC",
    "foto": "https://flagcdn.com/mc.svg",
    "emoji": "🇲🇨",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Mongolia",
    "paiscode": 976,
    "code": "MN",
    "foto": "https://flagcdn.com/mn.svg",
    "emoji": "🇲🇳",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Montenegro",
    "paiscode": 382,
    "code": "ME",
    "foto": "https://flagcdn.com/me.svg",
    "emoji": "🇲🇪",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Mozambique",
    "paiscode": 258,
    "code": "MZ",
    "foto": "https://flagcdn.com/mz.svg",
    "emoji": "🇲🇿",
    "latinAmerica": false,
    "phoneLength": 12,
  },
  {
    "response": "Namibia",
    "paiscode": 264,
    "code": "NA",
    "foto": "https://flagcdn.com/na.svg",
    "emoji": "🇳🇦",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Nauru",
    "paiscode": 674,
    "code": "NR",
    "foto": "https://flagcdn.com/nr.svg",
    "emoji": "🇳🇷",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Nepal",
    "paiscode": 977,
    "code": "NP",
    "foto": "https://flagcdn.com/np.svg",
    "emoji": "🇳🇵",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "Nicaragua",
    "paiscode": 505,
    "code": "NI",
    "foto": "https://flagcdn.com/ni.svg",
    "emoji": "🇳🇮",
    "latinAmerica": true,
    "phoneLength": 8,
  },
  {
    "response": "Níger",
    "paiscode": 227,
    "code": "NE",
    "foto": "https://flagcdn.com/ne.svg",
    "emoji": "🇳🇪",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Nigeria",
    "paiscode": 234,
    "code": "NG",
    "foto": "https://flagcdn.com/ng.svg",
    "emoji": "🇳🇬",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Noruega",
    "paiscode": 47,
    "code": "NO",
    "foto": "https://flagcdn.com/no.svg",
    "emoji": "🇳🇴",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Nueva Zelanda",
    "paiscode": 64,
    "code": "NZ",
    "foto": "https://flagcdn.com/nz.svg",
    "emoji": "🇳🇿",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Omán",
    "paiscode": 968,
    "code": "OM",
    "foto": "https://flagcdn.com/om.svg",
    "emoji": "🇴🇲",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Países Bajos",
    "paiscode": 31,
    "code": "NL",
    "foto": "https://flagcdn.com/nl.svg",
    "emoji": "🇳🇱",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Pakistán",
    "paiscode": 92,
    "code": "PK",
    "foto": "https://flagcdn.com/pk.svg",
    "emoji": "🇵🇰",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "Palaos",
    "paiscode": 680,
    "code": "PW",
    "foto": "https://flagcdn.com/pw.svg",
    "emoji": "🇵🇼",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Panamá",
    "paiscode": 507,
    "code": "PA",
    "foto": "https://flagcdn.com/pa.svg",
    "emoji": "🇵🇦",
    "latinAmerica": true,
    "phoneLength": 8,
  },
  {
    "response": "Papúa Nueva Guinea",
    "paiscode": 675,
    "code": "PG",
    "foto": "https://flagcdn.com/pg.svg",
    "emoji": "🇵🇬",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Paraguay",
    "paiscode": 595,
    "code": "PY",
    "foto": "https://flagcdn.com/py.svg",
    "emoji": "🇵🇾",
    "latinAmerica": true,
    "phoneLength": 9,
  },
  {
    "response": "Perú",
    "paiscode": 51,
    "code": "PE",
    "foto": "https://flagcdn.com/pe.svg",
    "emoji": "🇵🇪",
    "latinAmerica": true,
    "phoneLength": 9,
  },
  {
    "response": "Polonia",
    "paiscode": 48,
    "code": "PL",
    "foto": "https://flagcdn.com/pl.svg",
    "emoji": "🇵🇱",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Portugal",
    "paiscode": 351,
    "code": "PT",
    "foto": "https://flagcdn.com/pt.svg",
    "emoji": "🇵🇹",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Reino Unido",
    "paiscode": 44,
    "code": "GB",
    "foto": "https://flagcdn.com/gb.svg",
    "emoji": "🇬🇧",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "República Centroafricana",
    "paiscode": 236,
    "code": "CF",
    "foto": "https://flagcdn.com/cf.svg",
    "emoji": "🇨🇫",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "República Checa",
    "paiscode": 420,
    "code": "CZ",
    "foto": "https://flagcdn.com/cz.svg",
    "emoji": "🇨🇿",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "República del Congo",
    "paiscode": 243,
    "code": "CD",
    "foto": "https://flagcdn.com/cd.svg",
    "emoji": "🇨🇩",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "República Dominicana",
    "paiscode": 1809,
    "code": "DO",
    "foto": "https://flagcdn.com/do.svg",
    "emoji": "🇩🇴",
    "latinAmerica": true,
    "phoneLength": 10,
  },
  {
    "response": "Ruanda",
    "paiscode": 250,
    "code": "RW",
    "foto": "https://flagcdn.com/rw.svg",
    "emoji": "🇷🇼",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Rumania",
    "paiscode": 40,
    "code": "RO",
    "foto": "https://flagcdn.com/ro.svg",
    "emoji": "🇷🇴",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "Rusia",
    "paiscode": 7,
    "code": "RU",
    "foto": "https://flagcdn.com/ru.svg",
    "emoji": "🇷🇺",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "Samoa",
    "paiscode": 685,
    "code": "WS",
    "foto": "https://flagcdn.com/ws.svg",
    "emoji": "🇼🇸",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "San Cristóbal y Nieves",
    "paiscode": 1869,
    "code": "KN",
    "foto": "https://flagcdn.com/kn.svg",
    "emoji": "🇰🇳",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "San Marino",
    "paiscode": 378,
    "code": "SM",
    "foto": "https://flagcdn.com/sm.svg",
    "emoji": "🇸🇲",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "Santa Lucía",
    "paiscode": 1758,
    "code": "LC",
    "foto": "https://flagcdn.com/lc.svg",
    "emoji": "🇱🇨",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Santo Tomé y Príncipe",
    "paiscode": 239,
    "code": "ST",
    "foto": "https://flagcdn.com/st.svg",
    "emoji": "🇸🇹",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "San Vicente y las Granadinas",
    "paiscode": 1784,
    "code": "VC",
    "foto": "https://flagcdn.com/vc.svg",
    "emoji": "🇻🇨",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Senegal",
    "paiscode": 221,
    "code": "SN",
    "foto": "https://flagcdn.com/sn.svg",
    "emoji": "🇸🇳",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Serbia",
    "paiscode": 381,
    "code": "RS",
    "foto": "https://flagcdn.com/rs.svg",
    "emoji": "🇷🇸",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Seychelles",
    "paiscode": 248,
    "code": "SC",
    "foto": "https://flagcdn.com/sc.svg",
    "emoji": "🇸🇨",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Sierra Leona",
    "paiscode": 232,
    "code": "SL",
    "foto": "https://flagcdn.com/sl.svg",
    "emoji": "🇸🇱",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Singapur",
    "paiscode": 65,
    "code": "SG",
    "foto": "https://flagcdn.com/sg.svg",
    "emoji": "🇸🇬",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Siria",
    "paiscode": 963,
    "code": "SY",
    "foto": "https://flagcdn.com/sy.svg",
    "emoji": "🇸🇾",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Somalia",
    "paiscode": 252,
    "code": "SO",
    "foto": "https://flagcdn.com/so.svg",
    "emoji": "🇸🇴",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Sri Lanka",
    "paiscode": 94,
    "code": "LK",
    "foto": "https://flagcdn.com/lk.svg",
    "emoji": "🇱🇰",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Sudáfrica",
    "paiscode": 27,
    "code": "ZA",
    "foto": "https://flagcdn.com/za.svg",
    "emoji": "🇿🇦",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Sudán",
    "paiscode": 249,
    "code": "SD",
    "foto": "https://flagcdn.com/sd.svg",
    "emoji": "🇸🇩",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Sudán del Sur",
    "paiscode": 211,
    "code": "SS",
    "foto": "https://flagcdn.com/ss.svg",
    "emoji": "🇸🇸",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Suecia",
    "paiscode": 46,
    "code": "SE",
    "foto": "https://flagcdn.com/se.svg",
    "emoji": "🇸🇪",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Suiza",
    "paiscode": 41,
    "code": "CH",
    "foto": "https://flagcdn.com/ch.svg",
    "emoji": "🇨🇭",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Surinam",
    "paiscode": 597,
    "code": "SR",
    "foto": "https://flagcdn.com/sr.svg",
    "emoji": "🇸🇷",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Tailandia",
    "paiscode": 66,
    "code": "TH",
    "foto": "https://flagcdn.com/th.svg",
    "emoji": "🇹🇭",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Tanzania",
    "paiscode": 255,
    "code": "TZ",
    "foto": "https://flagcdn.com/tz.svg",
    "emoji": "🇹🇿",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Tayikistán",
    "paiscode": 992,
    "code": "TJ",
    "foto": "https://flagcdn.com/tj.svg",
    "emoji": "🇹🇯",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Timor Oriental",
    "paiscode": 670,
    "code": "TL",
    "foto": "https://flagcdn.com/tl.svg",
    "emoji": "🇹🇱",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Togo",
    "paiscode": 228,
    "code": "TG",
    "foto": "https://flagcdn.com/tg.svg",
    "emoji": "🇹🇬",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Tonga",
    "paiscode": 676,
    "code": "TO",
    "foto": "https://flagcdn.com/to.svg",
    "emoji": "🇹🇴",
    "latinAmerica": false,
    "phoneLength": 5,
  },
  {
    "response": "Trinidad y Tobago",
    "paiscode": 1868,
    "code": "TT",
    "foto": "https://flagcdn.com/tt.svg",
    "emoji": "🇹🇹",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Túnez",
    "paiscode": 216,
    "code": "TN",
    "foto": "https://flagcdn.com/tn.svg",
    "emoji": "🇹🇳",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Turkmenistán",
    "paiscode": 993,
    "code": "TM",
    "foto": "https://flagcdn.com/tm.svg",
    "emoji": "🇹🇲",
    "latinAmerica": false,
    "phoneLength": 8,
  },
  {
    "response": "Turquía",
    "paiscode": 90,
    "code": "TR",
    "foto": "https://flagcdn.com/tr.svg",
    "emoji": "🇹🇷",
    "latinAmerica": false,
    "phoneLength": 11,
  },
  {
    "response": "Tuvalu",
    "paiscode": 688,
    "code": "TV",
    "foto": "https://flagcdn.com/tv.svg",
    "emoji": "🇹🇻",
    "latinAmerica": false,
    "phoneLength": 5,
  },
  {
    "response": "Ucrania",
    "paiscode": 380,
    "code": "UA",
    "foto": "https://flagcdn.com/ua.svg",
    "emoji": "🇺🇦",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Uganda",
    "paiscode": 256,
    "code": "UG",
    "foto": "https://flagcdn.com/ug.svg",
    "emoji": "🇺🇬",
    "latinAmerica": false,
    "phoneLength": 7,
  },
  {
    "response": "Uruguay",
    "paiscode": 598,
    "code": "UY",
    "foto": "https://flagcdn.com/uy.svg",
    "emoji": "🇺🇾",
    "latinAmerica": true,
    "phoneLength": 8,
  },
  {
    "response": "Uzbekistán",
    "paiscode": 998,
    "code": "UZ",
    "foto": "https://flagcdn.com/uz.svg",
    "emoji": "🇺🇿",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Vanuatu",
    "paiscode": 678,
    "code": "VU",
    "foto": "https://flagcdn.com/vu.svg",
    "emoji": "🇻🇺",
    "latinAmerica": false,
    "phoneLength": 5,
  },
  {
    "response": "Venezuela",
    "paiscode": 58,
    "code": "VE",
    "foto": "https://flagcdn.com/ve.svg",
    "emoji": "🇻🇪",
    "latinAmerica": true,
    "phoneLength": 7,
  },
  {
    "response": "Vietnam",
    "paiscode": 84,
    "code": "VN",
    "foto": "https://flagcdn.com/vn.svg",
    "emoji": "🇻🇳",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Yemen",
    "paiscode": 967,
    "code": "YE",
    "foto": "https://flagcdn.com/ye.svg",
    "emoji": "🇾🇪",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Yibuti",
    "paiscode": 253,
    "code": "DJ",
    "foto": "https://flagcdn.com/dj.svg",
    "emoji": "🇩🇯",
    "latinAmerica": false,
    "phoneLength": 10,
  },
  {
    "response": "Zambia",
    "paiscode": 260,
    "code": "ZM",
    "foto": "https://flagcdn.com/zm.svg",
    "emoji": "🇿🇲",
    "latinAmerica": false,
    "phoneLength": 9,
  },
  {
    "response": "Zimbabue",
    "paiscode": 263,
    "code": "ZW",
    "foto": "https://flagcdn.com/zw.svg",
    "emoji": "🇿🇼",
    "latinAmerica": false,
    "phoneLength": 9,
  },
];